spring:
  application:
    name: config

  cloud:
    config:
      server:
        git:
          #  Git仓库网址
          uri: https://github.com/GuiYang175/spring-cloud-config
          #  Git用户名
          username: 1641074950@qq.com
          #  Git密码
          password: guiyang123456789
